### ISSUE TITLE
在临时部署中禁用 gitcus

### ISSUE THREAD

**Issue by caiyih** [NEUQ-CS/manual#19]
由于gitcus使用URL匹配来确定文章页面。在临时部署中进行交互会导致不可预知的结果，因此需要禁用gitcus评论系统

**Comment by Yttehs-HDX** [comment]
能否将匹配机制换成pathname解决

**Comment by caiyih** [comment]
改匹配模式的话现有的内容就全丢失了

**Comment by caiyih** [comment]
我咋开得的小号

**Comment by Yttehs-HDX** [comment]
那么以后域名也不能换了？
能不能对discussion的内容进行更改，适应新模式

**Comment by Cai1Hsu** [comment]
TODO
- [X] 迁移映射模式
- [ ] 迁移已有内容的标题
